server.port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/barofish-refactor
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        default_batch_fetch_size: 150
    show-sql: true
#    open-in-view: false

  flyway:
    enabled: true

  jwt:
    secret: embqxqDWXvSsdfeArcnN7vuxErQjfskqaMswsX9dfen9sTbyCMkpeNJz5w3FLWkxCfGVTgZ59kgJcKvewef9dYeM9QYsjccJcN5YjbfafK5dGrBDzpdwefabfDx82BNA6WJDFL2b7bUHL
    jwtExpirationInMs: 86400

logging:
  level:
    org:
      hibernate:
        type: trace
        persister:
          entity:
            WARN

utils:
  aes256:
    secret-key: "barofish"