version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: barofish-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: barofish-refactor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 초기 SQL 스크립트 실행 가능

volumes:
  mysql_data:
    driver: local